{"name": "Product consultation", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:33:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:53:10)\n", "trace": "  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\product_steps.py\", line 39, in step_impl\n    product_screen.assert_text(\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\Behave\\utils\\common_actions.py\", line 19, in assert_text\n    element_text = self.find_element(*locator).text\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\Behave\\utils\\common_actions.py\", line 16, in find_element\n    return self.driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 387, in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "description": "Verificación de inicio de sesión exitoso", "steps": [{"name": "Given login", "status": "passed", "start": 1688322360745, "stop": 1688322363845}, {"name": "Given the user makes tap in the button of a product", "status": "passed", "start": 1688322363845, "stop": 1688322366997}, {"name": "Then must be shown the product detail", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:33:12)\n    at AndroidUiautomator2Driver.findElement (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:53:10)\n", "trace": "  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\product_steps.py\", line 39, in step_impl\n    product_screen.assert_text(\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\Behave\\utils\\common_actions.py\", line 19, in assert_text\n    element_text = self.find_element(*locator).text\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\Behave\\utils\\common_actions.py\", line 16, in find_element\n    return self.driver.find_element(*locator)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 387, in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"E:\\Users\\314511\\PycharmProjects\\baz_behave\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1688322366997, "stop": 1688322387251}], "start": 1688322344444, "stop": 1688322387951, "uuid": "caae5320-3257-47b9-91fa-b448eacd8048", "historyId": "d2218331a81ac4319a970d60baeeb49c", "fullName": "Product detail: Product consultation", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "regression"}, {"name": "feature", "value": "Product detail"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}